nome = str(input('Digite seu nome: ')).strip()
lista = nome.split()
print('Analizando seu nome...')
print('Seu nome em maiusculas é {}'.format(nome.upper()))
print('Seu nome em minusculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
print('Seu nome é {} e tem {} letras'.format(lista[0], len(lista[0])))